apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cicd-demo2-deploy
  namespace: cicd-test
  labels:
    app: cicd-demo2
    env: cicd-test
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: cicd-demo2
        env: cicd-test
    spec:
      containers:
      - name: demo2
        image: deploymentcoe/cicd-demo2
        imagePullPolicy: Always
        ports:
         - containerPort: 8080