apiVersion: v1
kind: Service
metadata:
  name: cicd-demo3-svc
  namespace: cicd-test
spec:
  type: NodePort
  selector:
    app: cicd-demo3
  ports:
  - name: cicd-demo3-port
    port: 7073
    targetPort: 9090
  externalIPs:
    - 10.101.0.2
